### ISSUE TITLE
Cannot read properties of undefined (reading 'tree')

### ISSUE THREAD

**Issue by dsclassen** [blugavere/mongoose-to-swagger#2]
I am receiving the following error:

```
/home/xxxxxx/projects/xxxxxx/node_modules/mongoose-to-swagger/dist/index.js:139
    const tree = schema.tree;
                        ^

TypeError: Cannot read properties of undefined (reading 'tree')
    at getFieldsFromMongooseSchema (/home/xxxxxx/projects/xxxxxx/node_modules/mongoose-to-swagger/dist/index.js:139:25)
    at documentModel (/home/xxxxxx/projects/xxxxxx/node_modules/mongoose-to-swagger/dist/index.js:178:20)
    at Object.<anonymous> (/home/xxxxxx/projects/xxxxxx/openapi/swagger.js:11:30)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47
```

```
    "mongoose-to-swagger": "^1.5.1",
    "swagger-jsdoc": "^6.2.8",
```

I'm not sure if it matters, but the Mongooes schemas I am attempting to convert use [`discriminator`](https://mongoosejs.com/docs/discriminators.html) .

**Comment by dsclassen** [comment]
Here is an example of a Mongoose Schema that does not work:

```javascript
const mongoose = require('mongoose')
const Schema = mongoose.Schema

const jobSchema = new Schema(
  {
    title: {
      type: String,
      required: true
    }
  },
  {
    timestamps: true
  }
)

const fooJobSchema = new Schema(
  {
    foo: { type: String, required: true }
  },
  {
    timestamps: true
  }
)

const barJobSchema = new Schema(
  {
    bar: { type: String, required: true }
  },
  {
    timestamps: true
  }
)

const Job = mongoose.model('Job', jobSchema)
const FooJob = Job.discriminator('FooTypeJob', fooJobSchema)
const BarJob = Job.discriminator('BarTypeJob', barJobSchema)

module.exports = { Job, FooJob, BarJob }
```

and here is a swagger file


```javascript
const fs = require('fs')
const swaggerSpec = require('./swaggerOptions')
const m2s = require('mongoose-to-swagger')

const Job = require('../model/JobTest')

// Generate the Swagger definition for Mongoose/MongoDB schema
const jobSwaggerDefinition = m2s(Job)

swaggerSpec.components = swaggerSpec.components || {}
swaggerSpec.components.schemas = swaggerSpec.components.schemas || {}
swaggerSpec.components.schemas.Job = jobSwaggerDefinition

// Write the updated Swagger JSON to a file
fs.writeFileSync('openapi/v1/swagger_v1.json', JSON.stringify(swaggerSpec, null, 2))

```
